steps:
  - label: ":memo: Generate sentence"
    command: |
      python -c "import loremipsum; s=loremipsum.sentence(max_char=20); print(s); open('result.txt','w').write(s + '\\n')"
    key: generate_sentence
    artifact_paths:
      - result.txt
    plugins:
      - docker#v5.13.0:
          image: "python:3.13"
          always-pull: true
          propagate-uid-gid: true

  - label: ":writing_hand: Step with Annotation - Result 1"
    key: download_result_1
    command: |
      sh .buildkite/scripts/annotate_result.sh result.txt generate_sentence agent-cli-example success "Result # 1 output"
    artifact_paths:
      - result.txt
    depends_on: generate_sentence

  - label: ":memo: Generate sentence round 2"
    command: |
      python -c "import loremipsum; s=loremipsum.sentence(max_char=100); print(s); open('result2.txt','w').write(s + '\\n')"
    key: generate_sentence_2
    depends_on: download_result_1
    artifact_paths:
      - result2.txt
    plugins:
      - docker#v5.13.0:
          image: "python:3.13"
          always-pull: true
          propagate-uid-gid: true

  - label: ":writing_hand: Step with Annotation - Result 2"
    key: download_result_2
    command: |
      sh .buildkite/scripts/annotate_result.sh result2.txt generate_sentence_2 agent-cli-example-2 success "Result # 2 output"
    artifact_paths:
      - result2.txt
    depends_on: generate_sentence_2
